using Content.Shared.Shuttles.BUIStates;
using Content.Shared.Shuttles.Systems;
using Content.Shared.Shuttles.UI.MapObjects;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;

namespace Content.Client.Shuttles.UI;

[GenerateTypedNameReferences]
public sealed partial class BeaconScreen : BoxContainer
{
    private readonly List<ShuttleBeaconObject> _beacons = new();
    private FTLState _state;
    private int? _selected;

    public event Action<NetEntity, Angle>? RequestBeaconFTL;

    public BeaconScreen()
    {
        RobustXamlLoader.Load(this);

        BeaconList.OnItemSelected += args =>
        {
            _selected = args.ItemIndex;
            UpdateButton();
        };

        BeaconList.OnItemDeselected += _ =>
        {
            _selected = null;
            UpdateButton();
        };

        BeaconFTLButton.OnPressed += _ =>
        {
            if (_selected is not { } index || index < 0 || index >= _beacons.Count)
                return;

            RequestBeaconFTL?.Invoke(_beacons[index].Entity, Angle.Zero);
        };
    }

    public void UpdateState(ShuttleMapInterfaceState state)
    {
        _state = state.FTLState;

        if (SameBeacons(state.Destinations))
        {
            UpdateButton();
            return;
        }

        _selected = null;
        _beacons.Clear();
        _beacons.AddRange(state.Destinations);

        BeaconList.Clear();
        foreach (var beacon in _beacons)
        {
            BeaconList.AddItem(beacon.Name);
        }

        UpdateButton();
    }

    private bool SameBeacons(List<ShuttleBeaconObject> beacons)
    {
        if (_beacons.Count != beacons.Count)
            return false;

        for (var i = 0; i < _beacons.Count; i++)
        {
            if (_beacons[i].Entity != beacons[i].Entity || _beacons[i].Name != beacons[i].Name)
                return false;
        }

        return true;
    }

    private void UpdateButton()
    {
        BeaconFTLButton.Disabled = _state != FTLState.Available ||
                                   _selected == null ||
                                   _beacons.Count == 0;
    }
}
